version: '2'

services:
  proxy:
    build: nginx/
    container_name: "Portainer-WebProxy"
    ports:
      - "9000:80"
    networks:
      - local

  templates:
    build: templates/
    container_name: "Portainer-Templates"
    networks:
      - local

  portainer:
    image: portainer/portainer
    container_name: "Portainer-MainApp"
    command: --templates http://templates/templates.json
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data

  watchtower:
    image: centurylink/watchtower
    container_name: "Portainer-Watchtower"
    command: --cleanup portainer-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
